### ISSUE TITLE
tinyssh-convert usage error

### ISSUE THREAD

**Issue by jennydaman** [grazzolini/mkinitcpio-tinyssh#10]
The CLI for `tinyssh-convert` was (recently?) changed. Currently, trying to use this package causes:

```
  -> Running build hook: [tinyssh]
tinyssh-convert: usage: tinyssh-convert out-tinysshkeydir < in-opensshfile
```

https://github.com/grazzolini/mkinitcpio-tinyssh/blob/bd73e32a1685bb843cdfe1300abcad58faba6e88/tinyssh_install#L32

**Comment by bf** [comment]
@grazzolini can you please merge this? Thank you very much.

**Comment by saidie** [comment]
:+1: 
The patch works like a charm

**Comment by skaldesh** [comment]
ping

**Comment by cmm1107** [comment]
I tried the patch but the hook still doesn't appear to add the root_key.
forum post - https://bbs.archlinux.org/viewtopic.php?pid=2026202

**Comment by skaldesh** [comment]
@cmm1107 If you have run `mkinitcpio -P` once already, the directory `/etc/tinyssh/sshkeydir` probably already exists. The script then does not work correctly. Delete the directory and try again, you should then see a message that the OpenSSH keys have been successfully converted.

**Comment by cmm1107** [comment]
> @cmm1107 If you have run `mkinitcpio -P` once already, the directory `/etc/tinyssh/sshkeydir` probably already exists. The script then does not work correctly. Delete the directory and try again, you should then see a message that the OpenSSH keys have been successfully converted.

Thanks @skaldesh did a fresh install with the patch and saw key being added during mkinitcpio.

**Comment by decaby7e** [comment]
This is still broken on Arch for me as of today. Applying the patch posted above fixed the issue, but it would be nice if @grazzolini could merge this...

I replaced the check in `copy_openssh_keys()` for a cleaner install process:

```sh
if [ -d $destdir -a -x /usr/bin/tinyssh-convert ]; then
      rmdir $destdir
  fi
```

**Comment by AlbertoBoldrini** [comment]
@grazzolini can you please merge please?

**Comment by decaby7e** [comment]
Created an issue on the Arch bug tracker to attempt to fork this repo and take ownership of the package, as it seems to have been abandoned.

https://bugs.archlinux.org/task/74522?project=1&opened=37246

**Comment by goekce** [comment]
[mkinitcpio-systemd-tool](https://github.com/random-archer/mkinitcpio-systemd-tool) seems to be an alternative.

**Comment by Joseph-DiGiovanni** [comment]
@grazzolini I understand you no longer use tinyssh as per your comment on the archlinux bug tracker, but how hard is it to review and merge a 6 line PR? Certainly not over 3 years, and likely less time than it took you to write that comment.

**Comment by bf** [comment]
@Joseph-DiGiovanni instead of being negative here why don't we just fork it, merge it, package it, publish it, and maintain it in the future.

**Comment by Joseph-DiGiovanni** [comment]
@bf I can do both. I'll add it to the list of things everyone involved has had to waste their time and effort on so he could avoid a few clicks:
- Submitting a bug on the arch bug tracker
- Having to add a note of this issue to the arch wiki
- Everyone who needs to use this package having to update the script themselves
- Making a fork
- Merging the PR
- Getting the authors attention to update the package since he's also the official package maintainer

If @grazzolini reads this you may update the upstream URL to my [fork](https://github.com/Joseph-DiGiovanni/mkinitcpio-tinyssh). Thanks
